name: gcloud-githubactions-workflow
on:
  push:
    branches:
    - master
env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
jobs:
  upload-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Build Frontend
        run: |-
          npm install
          npm run build:ci
      - name: Setup - gcloud / gsutil
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true
      - name: Deploy
        run: |-
          gsutil web set -m index.html -e index.html gs://$GCS_BUCKET
          gsutil -m rsync -R dist/ gs://$GCS_BUCKET
          gsutil -m acl -r ch -u AllUsers:R gs://$GCS_BUCKET/*